### ISSUE TITLE
프로젝트 제안

### ISSUE THREAD

**Issue by sky4689524** [ComTalk/toy-community#2]
1. 주제:
2. 개요: 

위와 같은 양식으로 간단하게 Comment에 남겨주세요. 개요는 간단하게 2-3줄로 설명 부탁드립니다.

**Comment by ksron** [comment]
1. 주제: 맛집 종합 플랫폼. 맛집 큐레이팅
2. 개요: 
  - 카카오, 네이버, 인스타, 블로그, 구글지도 등등 데이터 종합
  - 주관적 평가/리뷰에 대한 객관적인 수치로 변환

**Comment by sky4689524** [comment]
1. 주제 : self-management platform
2. 개요:
-  자기 비서와 같은 역할을 수행. 예를 들어서 To-Do list, health, calendar, wallet 등의 기능을 오직 하나의 앱에서 구현.

**Comment by GOEON** [comment]
## 사진첩 자동 정리 프로그램 

1. 주제 : automation, saving space,  
2. 개요:
- 카메라 성능이 너무 좋아서, 이미지 한장 사이즈가 5MB ~ 10MB 는 기본이기 때문에 용량이 금방 찬다. 
- 비슷한 사진을 여러장 찍고, 나중에 지워야지 생각하지만 결코 나중은 오지 않는다. 
- 결국 manualy 사진을 지워주거나 백업을 해야 하는데, 사용자가 지우는 패턴을 학습해서 자동으로 사진첩에 지워야할 사진을 지워준다면?
- 혹은 지워야할 사진을 한 곳에 모아두고 사용자에게 허락을 받게 한다면?
- 웹 페이지는 대쉬보드 역할. 사진을 '사건' 단위로 요약하여 현재 사진첩에 어떤 사진이 모여 있는지 보여줄 수 있도록

**Comment by leesk0502** [comment]
**Fintech 서비스**
---
1. 주제 : 주식 매수/매도 추천 봇
2. 개요 :

- 기술적 지표, 알고리즘, AI 등에 따른 매수 / 매도 signal 발생해 주는 봇
- 알림의 형태는 슬랙, 텔레그램 메시지 notification
- 장전/장후 주요 뉴스, 종목 정량화하여 알려줌.
- 매수/매도 추천에 따른 일별 누적 수익률 축적, 가시화된 사이트 혹은 앱 제작
